apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocis-deployment
spec:
  selector:
    matchLabels:
      app: web
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: ocis
        image: ocisimage
